# dashboard/app.py
# Streamlit dashboard — three tabs:
#   Tab 1: Revenue Overview  — KPIs, daily trend, region breakdown
#   Tab 2: Products & Categories — product/category revenue, top customers
#   Tab 3: Data Quality — DQ check results, row counts, null rates, quarantine
#
# Reads from output/sales.duckdb (generated by pipeline/run_pipeline.py).

import os
import duckdb
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# -----------------------------------------------------------------------
# Config
# -----------------------------------------------------------------------
st.set_page_config(
    page_title="Sales Pipeline Dashboard — March 2025",
    page_icon="📊",
    layout="wide"
)

# Path to the DuckDB file — resolved to work locally AND on HF Spaces.
# On HF Spaces, app.py is the entrypoint at repo root, so CWD = repo root.
# Locally, app.py lives in dashboard/, so we walk up one level.
_here = os.path.dirname(os.path.abspath(__file__))
_candidates = [
    os.path.join(_here, "output", "sales.duckdb"),          # if run from dashboard/
    os.path.join(_here, "..", "output", "sales.duckdb"),     # standard local layout
    os.path.join(os.getcwd(), "output", "sales.duckdb"),     # HF Spaces / CWD
]
DB_PATH = next((p for p in _candidates if os.path.exists(p)), _candidates[1])


# -----------------------------------------------------------------------
# Database connection (cached so Streamlit doesn't reconnect on every render)
# -----------------------------------------------------------------------
@st.cache_resource
def get_connection():
    if not os.path.exists(DB_PATH):
        return None
    return duckdb.connect(DB_PATH, read_only=True)


@st.cache_data(ttl=300)
def query(_con, sql: str) -> pd.DataFrame:
    """Run a SQL query and return a DataFrame. Cached for 5 minutes."""
    return _con.execute(sql).df()


# -----------------------------------------------------------------------
# App header
# -----------------------------------------------------------------------
st.title("Sales Pipeline Dashboard — March 2025")
st.caption("Data pipeline: 30 daily CSVs -> DuckDB (raw -> clean -> fact). "
           "Run `python pipeline/run_pipeline.py` to regenerate.")

con = get_connection()
if con is None:
    st.error(
        f"Database not found at `{DB_PATH}`. "
        "Run `python pipeline/run_pipeline.py` first."
    )
    st.stop()

# -----------------------------------------------------------------------
# Tabs
# -----------------------------------------------------------------------
tab1, tab2, tab3 = st.tabs(["Revenue Overview", "Products & Categories", "Data Quality"])


# ═══════════════════════════════════════════════════════════════════════
# TAB 1: REVENUE OVERVIEW
# ═══════════════════════════════════════════════════════════════════════
with tab1:
    # ── KPI Cards ──────────────────────────────────────────────────────
    kpis = query(con, """
        SELECT
            ROUND(SUM(revenue), 2)          AS total_revenue,
            COUNT(*)                         AS total_orders,
            ROUND(AVG(revenue), 2)           AS avg_order_value,
            COUNT(DISTINCT customer_id)      AS unique_customers
        FROM fact_orders
    """).iloc[0]

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Revenue",      f"Rs. {kpis['total_revenue']:,.2f}")
    c2.metric("Total Orders",       f"{int(kpis['total_orders']):,}")
    c3.metric("Avg Order Value",    f"Rs. {kpis['avg_order_value']:,.2f}")
    c4.metric("Unique Customers",   f"{int(kpis['unique_customers']):,}")

    st.divider()

    # ── Daily Revenue Line Chart ───────────────────────────────────────
    daily = query(con, """
        SELECT order_date, total_revenue, order_count, is_weekend
        FROM daily_revenue
        ORDER BY order_date
    """)
    daily["order_date"] = pd.to_datetime(daily["order_date"])

    fig_daily = px.line(
        daily, x="order_date", y="total_revenue",
        title="Daily Revenue — March 2025",
        labels={"order_date": "Date", "total_revenue": "Revenue (Rs.)"},
        markers=True,
    )
    # Highlight weekends
    weekends = daily[daily["is_weekend"] == True]
    for _, row in weekends.iterrows():
        fig_daily.add_vrect(
            x0=str(row["order_date"]),
            x1=str(row["order_date"] + pd.Timedelta(days=1)),
            fillcolor="lightblue", opacity=0.2, line_width=0,
        )
    fig_daily.update_layout(showlegend=False)
    st.plotly_chart(fig_daily, use_container_width=True)

    st.caption("Light blue bands = weekends")

    st.divider()

    # ── Revenue by Region (stacked bar) ───────────────────────────────
    region_daily = query(con, """
        SELECT
            order_date,
            region,
            ROUND(SUM(revenue), 2) AS revenue
        FROM fact_orders
        GROUP BY order_date, region
        ORDER BY order_date, region
    """)
    region_daily["order_date"] = pd.to_datetime(region_daily["order_date"])

    fig_region = px.bar(
        region_daily, x="order_date", y="revenue", color="region",
        title="Daily Revenue by Region",
        labels={"order_date": "Date", "revenue": "Revenue (Rs.)", "region": "Region"},
        barmode="stack",
    )
    st.plotly_chart(fig_region, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════════
# TAB 2: PRODUCTS & CATEGORIES
# ═══════════════════════════════════════════════════════════════════════
with tab2:
    col_left, col_right = st.columns(2)

    # ── Revenue by Product (horizontal bar) ───────────────────────────
    with col_left:
        prod_rev = query(con, """
            SELECT
                p.product_name,
                ROUND(SUM(f.revenue), 2) AS revenue
            FROM fact_orders f
            JOIN dim_products p USING (product_id)
            GROUP BY p.product_name
            ORDER BY revenue DESC
        """)
        fig_prod = px.bar(
            prod_rev, x="revenue", y="product_name", orientation="h",
            title="Revenue by Product",
            labels={"revenue": "Revenue (Rs.)", "product_name": "Product"},
            color="revenue", color_continuous_scale="Blues",
        )
        fig_prod.update_layout(yaxis={"categoryorder": "total ascending"},
                               coloraxis_showscale=False)
        st.plotly_chart(fig_prod, use_container_width=True)

    # ── Revenue by Category (donut) ────────────────────────────────────
    with col_right:
        cat_rev = query(con, """
            SELECT
                category,
                ROUND(SUM(revenue), 2) AS revenue
            FROM fact_orders
            GROUP BY category
            ORDER BY revenue DESC
        """)
        fig_cat = px.pie(
            cat_rev, names="category", values="revenue",
            title="Revenue by Category",
            hole=0.4,
        )
        st.plotly_chart(fig_cat, use_container_width=True)

    st.divider()

    # ── Top 10 Customers by Spend ──────────────────────────────────────
    st.subheader("Top 10 Customers by Total Spend")
    top_customers = query(con, """
        SELECT
            customer_id,
            COUNT(*)                    AS orders,
            ROUND(SUM(revenue), 2)      AS total_spend,
            ROUND(AVG(revenue), 2)      AS avg_order
        FROM fact_orders
        GROUP BY customer_id
        ORDER BY total_spend DESC
        LIMIT 10
    """)
    top_customers.index = range(1, 11)
    st.dataframe(
        top_customers.rename(columns={
            "customer_id":  "Customer ID",
            "orders":       "Orders",
            "total_spend":  "Total Spend (Rs.)",
            "avg_order":    "Avg Order (Rs.)",
        }),
        use_container_width=True,
    )


# ═══════════════════════════════════════════════════════════════════════
# TAB 3: DATA QUALITY
# ═══════════════════════════════════════════════════════════════════════
with tab3:
    st.subheader("DQ Check Results")
    st.caption("Run after ingestion, before transformation. Results from last pipeline run.")

    # ── DQ Check Table ─────────────────────────────────────────────────
    dq = query(con, """
        SELECT check_name, status, details, rows_affected, run_timestamp
        FROM dq_results
        ORDER BY check_name
    """)

    def status_icon(s):
        return {"PASS": "✅ PASS", "WARN": "⚠️ WARN", "FAIL": "❌ FAIL"}.get(s, s)

    dq["status"] = dq["status"].map(status_icon)
    st.dataframe(
        dq.rename(columns={
            "check_name":    "Check",
            "status":        "Status",
            "details":       "Details",
            "rows_affected": "Rows Affected",
            "run_timestamp": "Run Timestamp",
        }),
        use_container_width=True,
        hide_index=True,
    )

    st.divider()

    col_a, col_b = st.columns(2)

    # ── Row Counts per Day ─────────────────────────────────────────────
    with col_a:
        st.subheader("Row Counts per Day (raw_orders)")
        rc = query(con, """
            SELECT _file_date AS file_date, COUNT(*) AS row_count
            FROM raw_orders
            GROUP BY _file_date
            ORDER BY _file_date
        """)
        rc["file_date"] = pd.to_datetime(rc["file_date"])

        fig_rc = px.bar(
            rc, x="file_date", y="row_count",
            title="Rows Loaded per Day",
            labels={"file_date": "File Date", "row_count": "Rows"},
            color="row_count",
            color_continuous_scale="RdYlGn",
            range_color=[5000, 10000],
        )
        fig_rc.add_hline(y=5000, line_dash="dash", line_color="red",
                         annotation_text="Min (5k)", annotation_position="bottom right")
        fig_rc.add_hline(y=10000, line_dash="dash", line_color="red",
                         annotation_text="Max (10k)")
        fig_rc.update_layout(coloraxis_showscale=False)
        st.plotly_chart(fig_rc, use_container_width=True)
        st.caption("Gaps in dates = missing files. Red dashed lines = expected row range.")

    # ── Quarantine Summary ─────────────────────────────────────────────
    with col_b:
        st.subheader("Quarantined Rows (excluded from revenue)")
        try:
            quar = query(con, """
                SELECT _file_date AS file_date, COUNT(*) AS quarantined
                FROM quarantine_orders
                GROUP BY _file_date
                ORDER BY _file_date
            """)
            if len(quar) == 0:
                st.success("No quarantined rows.")
            else:
                quar["file_date"] = pd.to_datetime(quar["file_date"])
                fig_quar = px.bar(
                    quar, x="file_date", y="quarantined",
                    title="Quarantined Rows per Day",
                    labels={"file_date": "File Date", "quarantined": "Rows"},
                    color_discrete_sequence=["#ef553b"],
                )
                st.plotly_chart(fig_quar, use_container_width=True)
                total_q = quar["quarantined"].sum()
                st.warning(
                    f"{total_q:,} rows quarantined (null critical fields). "
                    "Excluded from all revenue calculations."
                )
        except Exception:
            st.info("quarantine_orders table not found. Re-run the pipeline.")

    st.divider()

    # ── Duplicate Order IDs ────────────────────────────────────────────
    st.subheader("Duplicate Order IDs (before deduplication)")
    dups = query(con, """
        SELECT order_id, COUNT(*) AS occurrences, MIN(_source_file) AS file_1, MAX(_source_file) AS file_2
        FROM raw_orders
        WHERE order_id IS NOT NULL
        GROUP BY order_id
        HAVING COUNT(*) > 1
        ORDER BY occurrences DESC
        LIMIT 20
    """)
    if len(dups) == 0:
        st.success("No duplicate order_ids in raw_orders.")
    else:
        st.warning(f"{len(dups):,} duplicate order_ids found (showing up to 20). "
                   "Pipeline deduplicates before building fact_orders.")
        st.dataframe(dups, use_container_width=True, hide_index=True)

    st.divider()

    # ── Null Rates per Column ──────────────────────────────────────────
    st.subheader("Null Rates per Column (raw_orders)")
    cols_to_check = ["order_id", "customer_id", "product_id", "product_name",
                     "qty", "unit_price", "discount_pct", "region"]
    null_sql = " UNION ALL ".join(
        f"SELECT '{c}' AS col, "
        f"ROUND(100.0 * SUM(CASE WHEN {c} IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct "
        f"FROM raw_orders"
        for c in cols_to_check
    )
    null_df = query(con, null_sql)
    null_df = null_df.sort_values("null_pct", ascending=False)
    fig_null = px.bar(
        null_df, x="col", y="null_pct",
        title="Overall Null % per Column (raw_orders)",
        labels={"col": "Column", "null_pct": "Null %"},
        color="null_pct",
        color_continuous_scale="RdYlGn_r",
    )
    fig_null.add_hline(y=1, line_dash="dash", line_color="orange",
                       annotation_text="1% threshold")
    st.plotly_chart(fig_null, use_container_width=True)
