# dashboard/app.py — CFO-grade Sales Intelligence Dashboard
# Reads from output/sales.duckdb (generated by pipeline/run_pipeline.py).

import os
import duckdb
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Sales Intelligence — March 2025",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ── Professional CSS ───────────────────────────────────────────────────────────
st.markdown("""
<style>
  /* ── Global ── */
  [data-testid="stAppViewContainer"] { background: #0d1b2a; }
  [data-testid="stHeader"]           { background: #0d1b2a; }
  section[data-testid="stSidebar"]   { background: #0d1b2a; }
  .block-container { padding-top: 1.5rem; padding-bottom: 2rem; }

  /* ── Page title ── */
  .dash-title {
    background: linear-gradient(135deg, #0f2044 0%, #132d52 100%);
    border: 1px solid #1e3a4a;
    border-radius: 10px;
    padding: 22px 30px 18px;
    margin-bottom: 18px;
  }
  .dash-title .eyebrow {
    font-size: 10px; font-weight: 700; letter-spacing: 0.18em;
    color: #00c4ff; text-transform: uppercase; margin-bottom: 4px;
  }
  .dash-title h1 {
    font-size: 26px; font-weight: 800; color: #ffffff;
    margin: 0 0 4px 0; padding: 0; line-height: 1.2;
  }
  .dash-title .subtitle { font-size: 13px; color: #8fa3b1; margin: 0; }

  /* ── KPI cards ── */
  .kpi-grid { display: flex; gap: 14px; margin-bottom: 4px; }
  .kpi-card {
    flex: 1; background: #1a2b3c; border: 1px solid #1e3a4a;
    border-left: 3px solid #00c4ff; border-radius: 8px;
    padding: 18px 20px 14px;
  }
  .kpi-card .label  { font-size: 11px; font-weight: 600; letter-spacing: 0.08em;
                       color: #8fa3b1; text-transform: uppercase; margin-bottom: 6px; }
  .kpi-card .value  { font-size: 26px; font-weight: 800; color: #ffffff; line-height: 1.1; }
  .kpi-card .sub    { font-size: 11px; color: #4a7a9b; margin-top: 4px; }

  /* ── Section headers ── */
  .section-label {
    font-size: 11px; font-weight: 700; letter-spacing: 0.14em;
    color: #00c4ff; text-transform: uppercase;
    border-bottom: 1px solid #1e3a4a; padding-bottom: 6px; margin: 22px 0 12px;
  }

  /* ── Issue cards ── */
  .issue-card {
    border-radius: 8px; padding: 16px 18px; margin-bottom: 12px;
    border: 1px solid; position: relative;
  }
  .issue-critical { background: #1f0c0c; border-color: #7a1f1f; border-left: 4px solid #ff4b4b; }
  .issue-high     { background: #1f150c; border-color: #7a4a1f; border-left: 4px solid #ffa500; }
  .issue-medium   { background: #0c1020; border-color: #1f3a7a; border-left: 4px solid #4b9eff; }

  .issue-card .badge {
    display: inline-block; font-size: 9px; font-weight: 800; letter-spacing: 0.12em;
    padding: 2px 8px; border-radius: 3px; text-transform: uppercase; margin-bottom: 8px;
  }
  .badge-critical { background: #ff4b4b22; color: #ff4b4b; border: 1px solid #ff4b4b55; }
  .badge-high     { background: #ffa50022; color: #ffa500; border: 1px solid #ffa50055; }
  .badge-medium   { background: #4b9eff22; color: #4b9eff; border: 1px solid #4b9eff55; }

  .issue-card .issue-title {
    font-size: 15px; font-weight: 700; color: #ffffff; margin-bottom: 2px;
  }
  .issue-card .issue-date {
    font-size: 11px; color: #8fa3b1; margin-bottom: 8px;
  }
  .issue-card .issue-desc { font-size: 12px; color: #c0cfe0; line-height: 1.5; margin-bottom: 6px; }
  .issue-card .issue-fix  { font-size: 11px; color: #6b8fa6; line-height: 1.5; }
  .issue-card .resolved   {
    display: inline-block; font-size: 9px; font-weight: 700; letter-spacing: 0.1em;
    padding: 2px 8px; border-radius: 3px; background: #0a2a1a; color: #34d399;
    border: 1px solid #34d39944; text-transform: uppercase; margin-top: 8px;
  }

  /* ── Check table pill ── */
  .pill-pass { display:inline-block; padding:2px 10px; border-radius:12px; font-size:11px;
               font-weight:700; background:#0a2a1a; color:#34d399; border:1px solid #34d39944; }
  .pill-warn { display:inline-block; padding:2px 10px; border-radius:12px; font-size:11px;
               font-weight:700; background:#2a1a0a; color:#ffa500; border:1px solid #ffa50044; }
  .pill-fail { display:inline-block; padding:2px 10px; border-radius:12px; font-size:11px;
               font-weight:700; background:#2a0a0a; color:#ff4b4b; border:1px solid #ff4b4b44; }

  /* ── Streamlit overrides ── */
  .stTabs [data-baseweb="tab-list"]  { background: #0d1b2a; gap: 4px; border-bottom: 1px solid #1e3a4a; }
  .stTabs [data-baseweb="tab"]       { background: transparent; color: #8fa3b1;
                                        font-size: 13px; font-weight: 600; border-radius: 6px 6px 0 0;
                                        padding: 10px 20px; border: none; }
  .stTabs [aria-selected="true"]     { color: #ffffff !important; background: #1a2b3c !important;
                                        border-bottom: 2px solid #00c4ff !important; }
  .stMetric { display: none; }
  div[data-testid="stDataFrame"] { border-radius: 8px; overflow: hidden; }
  .stDivider { border-color: #1e3a4a !important; }
  h2, h3 { color: #ffffff !important; }
  p, li  { color: #c0cfe0 !important; }
  #MainMenu, footer { visibility: hidden; }
</style>
""", unsafe_allow_html=True)

# ── Constants ──────────────────────────────────────────────────────────────────
# DuckDB EXTRACT(DOW): 0=Sunday, 1=Monday … 6=Saturday
DOW_MAP   = {0: "Sun", 1: "Mon", 2: "Tue", 3: "Wed", 4: "Thu", 5: "Fri", 6: "Sat"}
DOW_ORDER = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

WEEK_COLORS = {
    "Week 1": "#4b9eff",
    "Week 2": "#00c4ff",
    "Week 3": "#a78bfa",
    "Week 4": "#34d399",
    "Week 5": "#fb923c",
}

# Confirmed DQ issue dates — used to annotate revenue chart
DQ_EVENTS = {
    "2025-03-15": {"label": "DUPE",   "color": "#ff4b4b", "short": "Duplication"},
    "2025-03-22": {"label": "SCHEMA", "color": "#4b9eff", "short": "Schema Drift"},
    "2025-03-26": {"label": "NULL",   "color": "#ffa500", "short": "Null Spike"},
    "2025-03-18": {"label": "LATE",   "color": "#a78bfa", "short": "Late File"},
}

# Pipeline check descriptions (matches quality_checks.py check names)
CHECK_DESC = {
    "row_counts":        "Validates each source file contains 5,000–10,000 rows. "
                         "Files outside range or missing dates are flagged.",
    "schema":            "Verifies all 10 expected columns exist in raw_orders after "
                         "ingest-time normalization (e.g. item_name → product_name).",
    "duplicates":        "Detects order_ids appearing in more than one source file. "
                         "Identifies re-deliveries such as March 15 re-sending March 14 data.",
    "date_completeness": "Checks every calendar date in March 2025 has at least one file "
                         "loaded. Flags missing delivery dates (e.g. March 31).",
    "null_rates":        "Measures per-file null % on critical columns: order_id, customer_id, "
                         "qty, unit_price, discount_pct. Any file exceeding 5% is flagged.",
}

CHART_LAYOUT = dict(
    template="plotly_dark",
    paper_bgcolor="#0d1b2a",
    plot_bgcolor="#0d1b2a",
    font=dict(family="Inter, system-ui, sans-serif", color="#c0cfe0"),
    title_font=dict(color="#ffffff", size=15),
    margin=dict(t=50, b=40, l=10, r=10),
)

GRID = dict(gridcolor="#1e3a4a", zerolinecolor="#1e3a4a")

# ── DB path resolution ─────────────────────────────────────────────────────────
_here = os.path.dirname(os.path.abspath(__file__))
_candidates = [
    os.path.join(_here, "output", "sales.duckdb"),
    os.path.join(_here, "..", "output", "sales.duckdb"),
    os.path.join(os.getcwd(), "output", "sales.duckdb"),
]
DB_PATH = next((p for p in _candidates if os.path.exists(p)), _candidates[1])


@st.cache_resource
def get_connection():
    if not os.path.exists(DB_PATH):
        return None
    return duckdb.connect(DB_PATH, read_only=True)


@st.cache_data(ttl=300)
def query(_con, sql: str) -> pd.DataFrame:
    return _con.execute(sql).df()


# ── Page header ────────────────────────────────────────────────────────────────
st.markdown("""
<div class="dash-title">
  <div class="eyebrow">Sales Intelligence Platform</div>
  <h1>March 2025 — Executive Revenue Summary</h1>
  <p class="subtitle">
    30 daily CSV files &nbsp;·&nbsp; DuckDB warehouse &nbsp;·&nbsp;
    4 data-quality issues detected &amp; resolved &nbsp;·&nbsp;
    Pipeline: ingest → validate → transform → model
  </p>
</div>
""", unsafe_allow_html=True)

con = get_connection()
if con is None:
    st.error(f"Database not found at `{DB_PATH}`. Run `python pipeline/run_pipeline.py` first.")
    st.stop()

# ── Tabs ───────────────────────────────────────────────────────────────────────
tab1, tab2, tab3 = st.tabs([
    "  Revenue Performance  ",
    "  Product Intelligence  ",
    "  Data Quality Audit  ",
])


# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 — REVENUE PERFORMANCE
# ══════════════════════════════════════════════════════════════════════════════
with tab1:

    # ── KPI Cards ──────────────────────────────────────────────────────────────
    kpis = query(con, """
        SELECT
            ROUND(SUM(revenue), 2)         AS total_revenue,
            COUNT(*)                        AS total_orders,
            ROUND(AVG(revenue), 2)          AS avg_order_value,
            COUNT(DISTINCT customer_id)     AS unique_customers
        FROM fact_orders
    """).iloc[0]

    st.markdown(f"""
    <div class="kpi-grid">
      <div class="kpi-card">
        <div class="label">Total Revenue</div>
        <div class="value">Rs. {kpis['total_revenue']:,.0f}</div>
        <div class="sub">March 2025 · clean orders only</div>
      </div>
      <div class="kpi-card">
        <div class="label">Orders Processed</div>
        <div class="value">{int(kpis['total_orders']):,}</div>
        <div class="sub">after deduplication</div>
      </div>
      <div class="kpi-card">
        <div class="label">Avg Order Value</div>
        <div class="value">Rs. {kpis['avg_order_value']:,.2f}</div>
        <div class="sub">per transaction</div>
      </div>
      <div class="kpi-card">
        <div class="label">Unique Customers</div>
        <div class="value">{int(kpis['unique_customers']):,}</div>
        <div class="sub">distinct customer IDs</div>
      </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<div style='height:12px'></div>", unsafe_allow_html=True)

    # ── Daily Revenue — annotated line chart ───────────────────────────────────
    st.markdown('<div class="section-label">Daily Revenue Trend</div>', unsafe_allow_html=True)

    daily = query(con, """
        SELECT order_date, total_revenue, order_count, is_weekend, day_of_week
        FROM daily_revenue
        ORDER BY order_date
    """)
    daily["order_date"] = pd.to_datetime(daily["order_date"])

    fig_daily = go.Figure()

    # Weekend shading
    for _, row in daily[daily["is_weekend"] == True].iterrows():
        fig_daily.add_vrect(
            x0=row["order_date"], x1=row["order_date"] + pd.Timedelta(days=1),
            fillcolor="#1e3a4a", opacity=0.45, line_width=0,
        )

    # DQ issue vertical lines
    for date_str, meta in DQ_EVENTS.items():
        fig_daily.add_vline(
            x=date_str, line_dash="dot", line_color=meta["color"], line_width=1.5,
        )
        fig_daily.add_annotation(
            x=date_str,
            y=daily["total_revenue"].max() * 1.04,
            text=f"<b>{meta['label']}</b>",
            showarrow=False,
            font=dict(color=meta["color"], size=9, family="Inter, sans-serif"),
            bgcolor="#0d1b2a",
            bordercolor=meta["color"],
            borderpad=3,
        )

    # Revenue line
    fig_daily.add_trace(go.Scatter(
        x=daily["order_date"],
        y=daily["total_revenue"],
        mode="lines+markers",
        line=dict(color="#00c4ff", width=2.5),
        marker=dict(size=5, color="#00c4ff"),
        customdata=daily[["order_count"]],
        hovertemplate=(
            "<b>%{x|%d %b %Y}</b><br>"
            "Revenue: Rs. %{y:,.0f}<br>"
            "Orders: %{customdata[0]:,}<extra></extra>"
        ),
        name="Daily Revenue",
    ))

    fig_daily.update_layout(
        **CHART_LAYOUT,
        height=320,
        showlegend=False,
        xaxis=dict(title="", **GRID, tickformat="%d %b"),
        yaxis=dict(title="Revenue (Rs.)", **GRID, tickformat=",.0f"),
        hovermode="x unified",
    )
    fig_daily.update_layout(
        annotations=fig_daily.layout.annotations + (
            go.layout.Annotation(
                x=0.01, y=-0.18, xref="paper", yref="paper",
                text="Shaded bands = weekends  ·  Dotted lines = DQ issue dates",
                showarrow=False, font=dict(size=10, color="#4a7a9b"),
            ),
        )
    )
    st.plotly_chart(fig_daily, use_container_width=True)

    # ── Week-over-Week Revenue by Day of Week ──────────────────────────────────
    st.markdown('<div class="section-label">Week-over-Week Pattern — Revenue by Day of Week</div>',
                unsafe_allow_html=True)

    wow_raw = query(con, """
        SELECT
            order_date,
            total_revenue,
            order_count,
            day_of_week,
            CASE
                WHEN EXTRACT(DAY FROM order_date) BETWEEN 1  AND 2  THEN 1
                WHEN EXTRACT(DAY FROM order_date) BETWEEN 3  AND 9  THEN 2
                WHEN EXTRACT(DAY FROM order_date) BETWEEN 10 AND 16 THEN 3
                WHEN EXTRACT(DAY FROM order_date) BETWEEN 17 AND 23 THEN 4
                WHEN EXTRACT(DAY FROM order_date) BETWEEN 24 AND 30 THEN 5
            END AS march_week
        FROM daily_revenue
        ORDER BY order_date
    """)
    wow_raw["order_date"] = pd.to_datetime(wow_raw["order_date"])
    wow_raw["dow_label"]  = wow_raw["day_of_week"].map(DOW_MAP)
    wow_raw["week_label"] = "Week " + wow_raw["march_week"].astype(int).astype(str)
    wow_raw["date_str"]   = wow_raw["order_date"].dt.strftime("%d %b")

    # sort within each week by canonical DOW order
    dow_sort = {d: i for i, d in enumerate(DOW_ORDER)}
    wow_raw["_dow_sort"] = wow_raw["dow_label"].map(dow_sort)
    wow_raw = wow_raw.sort_values(["march_week", "_dow_sort"])

    fig_wow = go.Figure()
    for week_label, grp in wow_raw.groupby("week_label", sort=True):
        grp = grp.sort_values("_dow_sort")
        fig_wow.add_trace(go.Scatter(
            x=grp["dow_label"],
            y=grp["total_revenue"],
            mode="lines+markers",
            name=week_label,
            line=dict(color=WEEK_COLORS.get(week_label, "#ffffff"), width=2.5),
            marker=dict(size=9, symbol="circle",
                        line=dict(color="#0d1b2a", width=1.5)),
            customdata=grp[["date_str", "order_count"]],
            hovertemplate=(
                f"<b>{{%x}}</b> ({week_label})<br>"
                "Date: %{customdata[0]}<br>"
                "Revenue: Rs. %{y:,.0f}<br>"
                "Orders: %{customdata[1]:,}<extra></extra>"
            ),
        ))

    fig_wow.update_layout(
        **CHART_LAYOUT,
        height=380,
        xaxis=dict(
            title="Day of Week",
            categoryorder="array",
            categoryarray=DOW_ORDER,
            **GRID,
        ),
        yaxis=dict(title="Revenue (Rs.)", tickformat=",.0f", **GRID),
        legend=dict(
            bgcolor="#1a2b3c", bordercolor="#1e3a4a", borderwidth=1,
            font=dict(size=11), title=dict(text="Week of March", font=dict(color="#8fa3b1")),
        ),
        hovermode="x unified",
    )
    st.plotly_chart(fig_wow, use_container_width=True)
    st.caption(
        "Week 1 = Mar 1–2 (Sat–Sun only) · Week 2 = Mar 3–9 · Week 3 = Mar 10–16 · "
        "Week 4 = Mar 17–23 · Week 5 = Mar 24–30  |  Mar 31 missing (no file delivered)"
    )


# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 — PRODUCT INTELLIGENCE
# ══════════════════════════════════════════════════════════════════════════════
with tab2:

    # ── Product + Category charts side-by-side ─────────────────────────────────
    st.markdown('<div class="section-label">Revenue Breakdown</div>', unsafe_allow_html=True)

    prod_rev = query(con, """
        SELECT
            p.product_name,
            p.category,
            ROUND(SUM(f.revenue), 2) AS revenue,
            COUNT(*)                  AS orders,
            ROUND(AVG(f.revenue), 2)  AS avg_rev
        FROM fact_orders f
        JOIN dim_products p USING (product_id)
        GROUP BY p.product_name, p.category
        ORDER BY revenue DESC
    """)

    cat_rev = query(con, """
        SELECT category, ROUND(SUM(revenue), 2) AS revenue
        FROM fact_orders
        GROUP BY category
        ORDER BY revenue DESC
    """)

    # Consistent category colors
    CAT_COLORS = {
        "Electronics":    "#00c4ff",
        "Apparel":        "#a78bfa",
        "Grocery":        "#34d399",
        "Stationery":     "#fb923c",
        "Home & Kitchen": "#f472b6",
    }
    prod_rev["color"] = prod_rev["category"].map(CAT_COLORS).fillna("#8fa3b1")

    col_left, col_right = st.columns([3, 2])

    with col_left:
        fig_prod = go.Figure(go.Bar(
            x=prod_rev["revenue"],
            y=prod_rev["product_name"],
            orientation="h",
            marker=dict(color=prod_rev["color"], opacity=0.9),
            customdata=prod_rev[["category", "orders", "avg_rev"]],
            hovertemplate=(
                "<b>%{y}</b><br>"
                "Category: %{customdata[0]}<br>"
                "Revenue: Rs. %{x:,.0f}<br>"
                "Orders: %{customdata[1]:,}<br>"
                "Avg: Rs. %{customdata[2]:,.2f}<extra></extra>"
            ),
        ))
        fig_prod.update_layout(
            **CHART_LAYOUT,
            title="Revenue by Product",
            height=420,
            showlegend=False,
            xaxis=dict(title="Revenue (Rs.)", tickformat=",.0f", **GRID),
            yaxis=dict(categoryorder="total ascending", **GRID),
        )
        st.plotly_chart(fig_prod, use_container_width=True)

    with col_right:
        fig_cat = go.Figure(go.Pie(
            labels=cat_rev["category"],
            values=cat_rev["revenue"],
            hole=0.52,
            marker=dict(colors=[CAT_COLORS.get(c, "#8fa3b1") for c in cat_rev["category"]],
                        line=dict(color="#0d1b2a", width=2)),
            textposition="inside",
            textinfo="percent+label",
            textfont=dict(size=11, color="#ffffff"),
            hovertemplate="<b>%{label}</b><br>Revenue: Rs. %{value:,.0f}<br>Share: %{percent}<extra></extra>",
        ))
        fig_cat.update_layout(
            **CHART_LAYOUT,
            title="Revenue by Category",
            height=420,
            showlegend=False,
        )
        fig_cat.add_annotation(
            text="By<br>Category", x=0.5, y=0.5, showarrow=False,
            font=dict(size=13, color="#8fa3b1"),
        )
        st.plotly_chart(fig_cat, use_container_width=True)

    st.markdown("<div style='height:4px'></div>", unsafe_allow_html=True)

    # ── Revenue by Region — multi-line over time ───────────────────────────────
    st.markdown('<div class="section-label">Regional Revenue Trend</div>', unsafe_allow_html=True)

    region_daily = query(con, """
        SELECT
            order_date,
            region,
            ROUND(SUM(revenue), 2) AS revenue,
            COUNT(*) AS orders
        FROM fact_orders
        GROUP BY order_date, region
        ORDER BY order_date, region
    """)
    region_daily["order_date"] = pd.to_datetime(region_daily["order_date"])

    REGION_COLORS = {"North": "#00c4ff", "South": "#34d399", "East": "#fb923c", "West": "#a78bfa"}

    fig_reg = go.Figure()
    for region, grp in region_daily.groupby("region"):
        grp = grp.sort_values("order_date")
        fig_reg.add_trace(go.Scatter(
            x=grp["order_date"],
            y=grp["revenue"],
            mode="lines+markers",
            name=region,
            line=dict(color=REGION_COLORS.get(region, "#8fa3b1"), width=2),
            marker=dict(size=4),
            customdata=grp[["orders"]],
            hovertemplate=(
                f"<b>{region}</b>  %{{x|%d %b}}<br>"
                "Revenue: Rs. %{y:,.0f}<br>"
                "Orders: %{customdata[0]:,}<extra></extra>"
            ),
        ))

    fig_reg.update_layout(
        **CHART_LAYOUT,
        title="Daily Revenue by Region",
        height=320,
        xaxis=dict(title="", tickformat="%d %b", **GRID),
        yaxis=dict(title="Revenue (Rs.)", tickformat=",.0f", **GRID),
        legend=dict(bgcolor="#1a2b3c", bordercolor="#1e3a4a", borderwidth=1),
        hovermode="x unified",
    )
    st.plotly_chart(fig_reg, use_container_width=True)

    # ── Top 10 Customers ───────────────────────────────────────────────────────
    st.markdown('<div class="section-label">Top 10 Customers by Total Spend</div>',
                unsafe_allow_html=True)

    top_cust = query(con, """
        SELECT
            customer_id                     AS "Customer ID",
            COUNT(*)                        AS "Orders",
            ROUND(SUM(revenue), 2)          AS "Total Spend (Rs.)",
            ROUND(AVG(revenue), 2)          AS "Avg Order (Rs.)",
            COUNT(DISTINCT product_id)      AS "Distinct Products"
        FROM fact_orders
        GROUP BY customer_id
        ORDER BY "Total Spend (Rs.)" DESC
        LIMIT 10
    """)
    top_cust.index = range(1, 11)
    st.dataframe(top_cust, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 3 — DATA QUALITY AUDIT
# ══════════════════════════════════════════════════════════════════════════════
with tab3:

    # ── 4 Confirmed Issues ─────────────────────────────────────────────────────
    st.markdown('<div class="section-label">Confirmed Data Quality Issues — 4 Found, 4 Resolved</div>',
                unsafe_allow_html=True)

    col_a, col_b = st.columns(2)

    with col_a:
        st.markdown("""
        <div class="issue-card issue-critical">
          <span class="badge badge-critical">CRITICAL</span>
          <div class="issue-title">Data Duplication</div>
          <div class="issue-date">sales_2025-03-15.csv</div>
          <div class="issue-desc">
            File is a complete re-delivery of March 14 data. All order timestamps
            show <strong>2025-03-14</strong> instead of March 15, causing every
            order_id to duplicate the prior day.
          </div>
          <div class="issue-fix">
            <strong>Impact:</strong> Would have double-counted ~6,100 rows of revenue.<br>
            <strong>Fix:</strong> Deduplicated on order_id (last-write-wins). Excess rows removed.
          </div>
          <span class="resolved">&#10003; Resolved</span>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("""
        <div class="issue-card issue-high">
          <span class="badge badge-high">HIGH</span>
          <div class="issue-title">Null Value Spike</div>
          <div class="issue-date">sales_2025-03-26.csv</div>
          <div class="issue-desc">
            Abnormally high null rates in critical revenue columns:
            <strong>unit_price</strong> (&gt;35% null) and
            <strong>product_name</strong> (&gt;20% null).
            Revenue cannot be calculated for these rows.
          </div>
          <div class="issue-fix">
            <strong>Impact:</strong> Thousands of rows would produce NULL revenue.<br>
            <strong>Fix:</strong> Rows quarantined before fact table load. Excluded from all metrics.
          </div>
          <span class="resolved">&#10003; Resolved</span>
        </div>
        """, unsafe_allow_html=True)

    with col_b:
        st.markdown("""
        <div class="issue-card issue-high">
          <span class="badge badge-high">HIGH</span>
          <div class="issue-title">Schema Drift</div>
          <div class="issue-date">sales_2025-03-22.csv</div>
          <div class="issue-desc">
            Column <strong>product_name</strong> was renamed to <strong>item_name</strong>
            by the upstream system, and an extra column <strong>channel</strong> was appended.
            A naive load would make product_name NULL for the entire day.
          </div>
          <div class="issue-fix">
            <strong>Impact:</strong> Full day of product data silently lost without normalization.<br>
            <strong>Fix:</strong> Ingest layer renames item_name → product_name; drops channel.
          </div>
          <span class="resolved">&#10003; Resolved</span>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("""
        <div class="issue-card issue-medium">
          <span class="badge badge-medium">MEDIUM</span>
          <div class="issue-title">Late File Delivery</div>
          <div class="issue-date">sales_2025-03-18.csv</div>
          <div class="issue-desc">
            File arrived in the <strong>late_arrivals/</strong> subdirectory rather
            than the main datasets folder. A naive glob on the main directory only
            would silently skip the entire day.
          </div>
          <div class="issue-fix">
            <strong>Impact:</strong> Full day of revenue (~March 18) would be missing from reports.<br>
            <strong>Fix:</strong> Pipeline scans both datasets/ and datasets/late_arrivals/ on every run.
          </div>
          <span class="resolved">&#10003; Resolved</span>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)

    # ── Pipeline Check Results ─────────────────────────────────────────────────
    st.markdown('<div class="section-label">Pipeline Check Results</div>', unsafe_allow_html=True)

    dq = query(con, """
        SELECT check_name, status, details, rows_affected, run_timestamp
        FROM dq_results
        ORDER BY check_name
    """)

    # Build enriched display table
    dq_display = dq.copy()
    dq_display["What It Checks"] = dq_display["check_name"].map(CHECK_DESC).fillna("—")

    STATUS_HTML = {
        "PASS": '<span class="pill-pass">PASS</span>',
        "WARN": '<span class="pill-warn">WARN</span>',
        "FAIL": '<span class="pill-fail">FAIL</span>',
    }

    # Show as styled HTML table
    rows_html = ""
    for _, r in dq_display.iterrows():
        pill = STATUS_HTML.get(r["status"], r["status"])
        rows_html += f"""
        <tr>
          <td style="color:#ffffff;font-weight:600;white-space:nowrap">{r['check_name']}</td>
          <td style="color:#8fa3b1;font-size:11px;max-width:260px">{r['What It Checks']}</td>
          <td>{pill}</td>
          <td style="color:#fb923c;text-align:right;font-weight:600">{int(r['rows_affected']):,}</td>
          <td style="color:#6b8fa6;font-size:11px">{r['details'][:120]}{'…' if len(r['details']) > 120 else ''}</td>
          <td style="color:#4a7a9b;font-size:10px;white-space:nowrap">{str(r['run_timestamp'])[:16]}</td>
        </tr>"""

    st.markdown(f"""
    <div style="overflow-x:auto">
    <table style="width:100%;border-collapse:collapse;font-family:Inter,sans-serif;font-size:12px">
      <thead>
        <tr style="border-bottom:1px solid #1e3a4a">
          <th style="text-align:left;padding:8px 12px;color:#8fa3b1;font-weight:600;text-transform:uppercase;font-size:10px;letter-spacing:0.08em">Check</th>
          <th style="text-align:left;padding:8px 12px;color:#8fa3b1;font-weight:600;text-transform:uppercase;font-size:10px;letter-spacing:0.08em">What It Validates</th>
          <th style="text-align:left;padding:8px 12px;color:#8fa3b1;font-weight:600;text-transform:uppercase;font-size:10px;letter-spacing:0.08em">Status</th>
          <th style="text-align:right;padding:8px 12px;color:#8fa3b1;font-weight:600;text-transform:uppercase;font-size:10px;letter-spacing:0.08em">Rows</th>
          <th style="text-align:left;padding:8px 12px;color:#8fa3b1;font-weight:600;text-transform:uppercase;font-size:10px;letter-spacing:0.08em">Details</th>
          <th style="text-align:left;padding:8px 12px;color:#8fa3b1;font-weight:600;text-transform:uppercase;font-size:10px;letter-spacing:0.08em">Run At</th>
        </tr>
      </thead>
      <tbody>
        {rows_html}
      </tbody>
    </table>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<div style='height:16px'></div>", unsafe_allow_html=True)

    # ── Null Rate Heatmap ──────────────────────────────────────────────────────
    st.markdown('<div class="section-label">Null Rate Heatmap — Column × File Date</div>',
                unsafe_allow_html=True)

    null_wide = query(con, """
        SELECT
            CAST(_file_date AS VARCHAR)                                                   AS file_date,
            ROUND(100.0 * SUM(CASE WHEN order_id      IS NULL THEN 1 ELSE 0 END)/COUNT(*),1) AS order_id,
            ROUND(100.0 * SUM(CASE WHEN customer_id   IS NULL THEN 1 ELSE 0 END)/COUNT(*),1) AS customer_id,
            ROUND(100.0 * SUM(CASE WHEN product_id    IS NULL THEN 1 ELSE 0 END)/COUNT(*),1) AS product_id,
            ROUND(100.0 * SUM(CASE WHEN product_name  IS NULL THEN 1 ELSE 0 END)/COUNT(*),1) AS product_name,
            ROUND(100.0 * SUM(CASE WHEN category      IS NULL THEN 1 ELSE 0 END)/COUNT(*),1) AS category,
            ROUND(100.0 * SUM(CASE WHEN qty           IS NULL THEN 1 ELSE 0 END)/COUNT(*),1) AS qty,
            ROUND(100.0 * SUM(CASE WHEN unit_price    IS NULL THEN 1 ELSE 0 END)/COUNT(*),1) AS unit_price,
            ROUND(100.0 * SUM(CASE WHEN discount_pct  IS NULL THEN 1 ELSE 0 END)/COUNT(*),1) AS discount_pct,
            ROUND(100.0 * SUM(CASE WHEN region        IS NULL THEN 1 ELSE 0 END)/COUNT(*),1) AS region
        FROM raw_orders
        GROUP BY _file_date
        ORDER BY _file_date
    """)

    heat_cols = ["order_id", "customer_id", "product_id", "product_name",
                 "category", "qty", "unit_price", "discount_pct", "region"]
    null_long  = null_wide.melt(id_vars="file_date", value_vars=heat_cols,
                                var_name="column", value_name="null_pct")
    heat_matrix = null_long.pivot(index="column", columns="file_date", values="null_pct")
    # Shorten date labels: "2025-03-01" → "03-01"
    heat_matrix.columns = [c[5:] for c in heat_matrix.columns]

    fig_heat = go.Figure(go.Heatmap(
        z=heat_matrix.values,
        x=heat_matrix.columns.tolist(),
        y=heat_matrix.index.tolist(),
        colorscale=[
            [0.00, "#0d1b2a"],
            [0.01, "#1a2b3c"],
            [0.10, "#ffa50044"],
            [0.30, "#ffa500"],
            [1.00, "#ff4b4b"],
        ],
        zmin=0, zmax=100,
        text=heat_matrix.values,
        texttemplate="%{text:.0f}",
        textfont=dict(size=8, color="#ffffff"),
        hovertemplate="Date: %{x}<br>Column: %{y}<br>Null rate: %{z:.1f}%<extra></extra>",
        showscale=True,
        colorbar=dict(
            title=dict(text="Null %", font=dict(color="#8fa3b1", size=11)),
            ticksuffix="%",
            tickfont=dict(color="#8fa3b1"),
            thickness=12,
        ),
    ))
    fig_heat.update_layout(
        **CHART_LAYOUT,
        title="Null % per Column per Source File  (orange/red = problem zone)",
        height=360,
        xaxis=dict(title="File Date (MM-DD)", tickangle=-45,
                   tickfont=dict(size=9), **GRID),
        yaxis=dict(title="Column", autorange="reversed", tickfont=dict(size=11)),
        margin=dict(t=55, b=60, l=110, r=80),
    )
    st.plotly_chart(fig_heat, use_container_width=True)
    st.caption("Any cell above 5% (amber) warrants investigation. March 26 shows the null spike in unit_price and product_name.")

    # ── Row Counts per File ────────────────────────────────────────────────────
    st.markdown('<div class="section-label">Row Counts per Source File</div>', unsafe_allow_html=True)

    rc = query(con, """
        SELECT CAST(_file_date AS VARCHAR) AS file_date, COUNT(*) AS row_count
        FROM raw_orders
        GROUP BY _file_date
        ORDER BY _file_date
    """)
    rc["in_range"] = rc["row_count"].between(5000, 10000)
    rc["bar_color"] = rc["in_range"].map({True: "#34d399", False: "#ff4b4b"})

    fig_rc = go.Figure(go.Bar(
        x=rc["file_date"].str[5:],  # MM-DD only
        y=rc["row_count"],
        marker=dict(color=rc["bar_color"], opacity=0.85),
        hovertemplate="<b>%{x}</b><br>Rows: %{y:,}<extra></extra>",
    ))
    fig_rc.add_hline(y=5000,  line_dash="dot", line_color="#ff4b4b",
                     annotation_text="Min 5k",  annotation_font_color="#ff4b4b", annotation_font_size=10)
    fig_rc.add_hline(y=10000, line_dash="dot", line_color="#ff4b4b",
                     annotation_text="Max 10k", annotation_font_color="#ff4b4b", annotation_font_size=10)
    fig_rc.update_layout(
        **CHART_LAYOUT,
        title="Rows Loaded per Source File (green = within 5k–10k range)",
        height=300,
        showlegend=False,
        xaxis=dict(title="File Date (MM-DD)", tickangle=-45, tickfont=dict(size=9), **GRID),
        yaxis=dict(title="Row Count", tickformat=",", **GRID),
        margin=dict(t=50, b=60, l=60, r=10),
    )
    st.plotly_chart(fig_rc, use_container_width=True)

    # ── Duplicate Order IDs ────────────────────────────────────────────────────
    st.markdown('<div class="section-label">Duplicate Order IDs — Pre-Deduplication Snapshot</div>',
                unsafe_allow_html=True)

    dups = query(con, """
        SELECT
            order_id,
            COUNT(*) AS occurrences,
            MIN(_source_file) AS first_file,
            MAX(_source_file) AS last_file
        FROM raw_orders
        WHERE order_id IS NOT NULL
        GROUP BY order_id
        HAVING COUNT(*) > 1
        ORDER BY occurrences DESC
        LIMIT 25
    """)

    if len(dups) == 0:
        st.success("No duplicate order_ids found in raw_orders.")
    else:
        total_excess = int(dups["occurrences"].sum() - len(dups))
        st.warning(
            f"{len(dups):,} duplicate order_ids detected ({total_excess:,} excess rows total). "
            "All resolved by the deduplication step in transform.py — fact_orders contains only unique order_ids.",
            icon="⚠️",
        )
        st.dataframe(dups, use_container_width=True, hide_index=True)

    # ── Quarantine Summary ─────────────────────────────────────────────────────
    st.markdown('<div class="section-label">Quarantine Summary — Rows Excluded from Revenue</div>',
                unsafe_allow_html=True)
    try:
        quar = query(con, """
            SELECT CAST(_file_date AS VARCHAR) AS file_date, COUNT(*) AS quarantined
            FROM quarantine_orders
            GROUP BY _file_date
            ORDER BY _file_date
        """)
        if len(quar) == 0:
            st.success("No quarantined rows — all loaded rows met quality thresholds.")
        else:
            total_q = int(quar["quarantined"].sum())
            st.warning(
                f"{total_q:,} rows quarantined (NULL in a critical revenue field). "
                "These rows exist in quarantine_orders and are fully excluded from fact_orders and all revenue metrics.",
                icon="⚠️",
            )
            fig_quar = go.Figure(go.Bar(
                x=quar["file_date"].str[5:],
                y=quar["quarantined"],
                marker=dict(color="#ff4b4b", opacity=0.8),
                hovertemplate="<b>%{x}</b><br>Quarantined: %{y:,}<extra></extra>",
            ))
            fig_quar.update_layout(
                **CHART_LAYOUT,
                title="Quarantined Rows per Source File",
                height=260,
                showlegend=False,
                xaxis=dict(title="File Date (MM-DD)", tickangle=-45,
                           tickfont=dict(size=9), **GRID),
                yaxis=dict(title="Rows Quarantined", tickformat=",", **GRID),
                margin=dict(t=50, b=60, l=60, r=10),
            )
            st.plotly_chart(fig_quar, use_container_width=True)
    except Exception:
        st.info("quarantine_orders table not found. Re-run the pipeline to generate it.")
