# dashboard/app.py
# Streamlit dashboard — three tabs: Revenue Overview, Products & Categories, DQ Status.
# Reads from output/sales.duckdb (generated by pipeline/run_pipeline.py).

import streamlit as st

st.set_page_config(page_title="Sales Pipeline Dashboard", layout="wide")
st.title("Sales Pipeline Dashboard — March 2025")
st.info("Run `python pipeline/run_pipeline.py` first to generate the database.")

# TODO: implement in Phases 6 (Tabs 1-2) and 7 (Tab 3: DQ Status)
